import Head from 'next/head'

import Homepage from "src/Homepage/Homepage"

const Index = () => {
  return (<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage/>
  </>)
}

export default Index